antibiotics = [
    "Cefpodoxime Proxetil",
    "Cefotaxime",
    "Cefixime+Ambroxol+Lactobacillus",
    "Cefixime+Saccharomyces boulardii+Lactobacillus",
    "Imipenem",
    "Piperacillin+Tazobactum",
    "Cefixime+Ornidazole",
    "Ceftazidime+Sulbactam",
    "Ciprofloxacin+Tinidazole",
    "Cefuroxime",
    "Cefpodoxime Proxetil+Lactobacillus",
    "Doripenem",
    "Cefixime+Probiotics",
    "Ofloxacin+Ornidazole",
    "Cefepime+Tazobactam",
    "Meropenem",
    "Cotrimoxazole",
    "Levofloxacin",
    "Clarithromycin",
    "Benzylpenicillin",
    "Linezolid",
    "Cefazolin",
    "Minocycline",
    "Azithromycin",
    "Metronidazole",
    "Erythromycin",
    "Chloramphenicol",
    "Clindamycin",
    "Tetracycline",
    "Vancomycin",
    "Amoxicillin",
    "Doxycycline",
    "Norfloxacin",
    "Ceftriaxone",
    "Ofloxacin",
    "Amikacin",
    "Fosfomycin",
    "Cefixime",
    "Clarithromycin+Pristinamycin",
    "Oxytetracycline",
    "Linezolid+Tedizolid",
    "Meropenem+Vaborbactam",
    "Clavulanic acid+Amoxicillin",
    "Nalidixic acid",
    "Tigecycline",
    "Ceftazidime",
    "Omadacycline",
    "Telavancin",
    "Rifaximin",
    "Eravacycline",
    "Ceftolozane+Tazobactam",
    "Tedizolid",
    "Sulfamethoxazole+Trimethoprim",
    "Avibactam+Ceftazidime",
    "Lefamulin",
    "Furazolidone",
    "Imipenem+Cilastatin",
    "Levofloxacin+Moxifloxacin",
    "Nitrofurantoin",
    "Moxifloxacin",
    "Piperacillin+Tazobactam",
    "Colistin",
    "Gatifloxacin",
    "Cefepime",
    "Linezolid+Vancomycin",
    "Prulifloxacin",
    "Spectinomycin",
    "Clindamycin+Metronidazole",
    "Oxazolidinone",
    "Amoxicillin+Clavulanic acid",
    "Quinupristin+Dalfopristin",
    "Vancomycin+Linezolid",
    "Amoxycillin+Cloxacillin",
    "Clavulanic acid",
    "Meropenem+Imipenem"
]
